# Generated by Django 4.2.2 on 2023-09-30 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('postgresql+psycopg2', 'PostgreSQL'), ('mysql+pymysql', 'MySQL'), ('oracle+cx_oracle', 'Oracle'), ('mssql+pyodbc', 'Microsoft SQL Server'), ('redshift+redshift_connector', 'Redshift'), ('https', 'Elastic search'), ('snowflake', 'Amazon Snowflake')], max_length=255, null=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('port', models.CharField(max_length=255, null=True)),
                ('db_name', models.CharField(max_length=255, null=True)),
                ('tables', models.CharField(max_length=255, null=True)),
                ('snowflake_account', models.CharField(help_text='Snowflake database account', max_length=255, null=True)),
                ('snowflake_schema', models.CharField(help_text='Snowflake database schema', max_length=255, null=True)),
                ('snowflake_warehouse', models.CharField(help_text='Snowflake database warehouse', max_length=255, null=True)),
                ('schema', models.TextField(null=True)),
                ('spec_url', models.URLField(help_text='Openapi spec url', null=True)),
                ('header', models.JSONField(help_text='A dict of API request header', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_db', models.BooleanField(default=False)),
                ('is_api', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_ai', models.BooleanField(default=False)),
                ('sql_query', models.CharField(max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.data')),
            ],
        ),
    ]
