# Generated by Django 4.2.2 on 2023-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp_auth_url_user_otp_base32_user_otp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateField(null=True),
        ),
    ]
