service: "${env:PROJECT_NAME}-workers"

provider:
  name: aws
  runtime: 'nodejs18.x'
  versionFunctions: false
  stage: "${env:ENV_STAGE}"
  region: "${env:AWS_DEFAULT_REGION}"
  stackName: ${self:custom.conf.stackName}
  iamRoleStatements: ${self:custom.conf.iam}
  environment: ${self:custom.conf.environment}
  apiGateway:
    websocketApiId: ${self:custom.conf.websocketApiId}
  tracing:
    lambda: true

functions:
  ScheduleTask:
    handler: scheduler.handlers.schedule_task
    runtime: python3.9
    timeout: 20
    memorySize: 128
    environment: ${self:custom.conf.ScheduleTask.environment}
    events:
      - eventBridge:
          eventBus: '${self:custom.conf.eventBusArn}'
          pattern:
            source:
              - backend.scheduler

  ExecuteScheduledTask:
    handler: scheduler.handlers.execute_task
    runtime: python3.9
    timeout: 6
    memorySize: 128
    environment: ${self:custom.conf.ExecuteScheduledTask.environment}

  SendEmail:
    handler: email.handlers.send_email
    timeout: 6
    memorySize: 128
    environment: ${self:custom.conf.SendEmail.environment}
    events:
      - eventBridge:
          eventBus: "${self:custom.conf.eventBusArn}"
          pattern:
            source:
              - backend.email
  
  WebSocketTask:
    handler: websocket.handlers.send_notification
    timeout: 6
    memorySize: 128
    environment: ${self:custom.conf.WebSocketTask.environment}
    events:
      - eventBridge:
          eventBus: "${self:custom.conf.eventBusArn}"
          pattern:
            source:
              - backend.websocket
  

plugins:
  - serverless-step-functions
  - serverless-esbuild
  - serverless-localstack

custom:
  projectEnvName: "${env:PROJECT_NAME}-${env:ENV_STAGE}"
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: false

  ssmService: env-${env:PROJECT_NAME}-${self:provider.stage}-workers

  esbuild: ${self:custom.conf.esbuild}

  conf: ${file(./${self:custom.confFile.${self:provider.stage}})}
  confFile:
    local: workers.conf.local.yml
    dev: workers.conf.yml
    qa: workers.conf.yml
    prod: workers.conf.yml

  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localstack  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: false  # optional - Start LocalStack in Docker on Serverless deploy

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .git/**
    - node_modules/**
    - aws/**

stepFunctions:
  stateMachines:
    TaskSchedulingStateMachine:
      id: TaskSchedulingStateMachineID
      name: "${opt:stage, self:provider.stage}-TaskSchedulingStateMachine"
      definition:
        Comment: "Schedules task execution"
        StartAt: WaitForDueDate
        States:
          WaitForDueDate:
            Type: Wait
            TimestampPath: "$.due_date"
            Next: Execute
          Execute:
            Type: Task
            Resource:
              Fn::GetAtt: [ ExecuteScheduledTask, Arn ]
            End: true
